export enum NOTIFICATION_TYPE_ENUM {
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  FRIEND_ACCEPTED = 'FRIEND_ACCEPTED',
  POST_COMMENT = 'POST_COMMENT',
  POST_COMMENT_LIKE = 'POST_COMMENT_LIKE',
  POST_COMMENT_REPLY = 'POST_COMMENT_REPLY',
  POST_COMMENT_REPLY_LIKE = 'POST_COMMENT_REPLY_LIKE',
  POST_COMMENT_REPLY_REPLY = 'POST_COMMENT_REPLY_REPLY',
  POST_COMMENT_REPLY_REPLY_LIKE = 'POST_COMMENT_REPLY_REPLY_LIKE',
  POST_SHARE = 'POST_SHARE',
  POST_TAG = 'POST_TAG',
  POST_TAGGED = 'POST_TAGGED',
  POST_REACTION = 'POST_REACTION',
  SYSTEM = 'SYSTEM',
  GROUP_INVITATION = 'GROUP_INVITATION',
  GROUP_JOIN_REQUEST = 'GROUP_JOIN_REQUEST',
  GROUP_JOIN_REQUEST_ACCEPTED = 'GROUP_JOIN_REQUEST_ACCEPTED',
  GROUP_JOIN_REQUEST_REJECTED = 'GROUP_JOIN_REQUEST_REJECTED',
  GROUP_JOIN_REQUEST_CANCELLED = 'GROUP_JOIN_REQUEST_CANCELLED',
}

export enum NOTIFICATION_STATUS_ENUM {
  UNREAD = 'UNREAD',
  READ = 'READ',
  DELETED = 'DELETED',
}

export enum NOTIFICATION_TEMPLATE_ENUM {
  'LIKE' = 'LIKE',
  'COMMENT' = 'COMMENT',
  'REPLY' = 'REPLY',
  'SHARE' = 'SHARE',
  'TAG' = 'TAG',
  'REACTION' = 'REACTION',
  'SYSTEM' = 'SYSTEM',
  'FRIEND_REQUEST' = 'FRIEND_REQUEST',
}
