services:
  # backend:
  #   image: khiemldk/social-network
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - '${PORT}:${PORT}'
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  postgres-data:
  mongo-data: