services:
  backend:
    image: khiemldk/social-network
    build: .
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: